version: 2.1
executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.13.1

# commands:
#   restore_yarn:
#     steps:
#       - restore_cache:
#           name: Restore yarn dependencies
#           key: yarn-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}

#   save_yarn:
#     steps:
#       - save_cache:
#           name: Cache yarn dependencies
#           key: yarn-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
#           paths:
#             - ./node_modules/

jobs:
  test_files:
    executor:
      name: default
    steps:
      - checkout
      - run:
          command: |
            npm config set prefix '~/.npm-global/'
            npm install -g firebase-tools
            cd ~/.npm-global/
            ls -l
            cd bin
            ls -l
            cd ../lib
            ls -l
            ~/.npm-global/bin/firebase --version

  # setup:
  #   executor:
  #     name: default
  #   steps:
  #     - checkout
  #     - restore_yarn
  #     - run:
  #         name: Install dependencies
  #         command: yarn --check-files --frozen-lockfile --non-interactive
  #     - save_yarn

  # format_and_lint:
  #   executor:
  #     name: default
  #   steps:
  #     - checkout
  #     - restore_yarn
  #     - run:
  #         command: yarn fix

  # build:
  #   executor:
  #     name: default
  #   steps:
  #     - checkout
  #     - restore_yarn
  #     - run:
  #         name: Create .env
  #         command: echo 'SKIP_PREFLIGHT_CHECK=true' > .env
  #     - run:
  #         name: Run build
  #         command: yarn build
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - build

  # deploy:
  #   parameters:
  #     env:
  #       type: enum
  #       enum: ["dev", "prod"]
  #   executor:
  #     name: default
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         command: ls -l
  #     - run:
  #         name: Install Firebase Tools
  #         command: npm install --prefix=./firebase-tools firebase-tools
  #     - run:
  #         name: Deploy to Firebase
  #         command: ./firebase-tools/node_modules/.bin/firebase deploy --only hosting --project << parameters.env >> --token ${FIREBASE_TOKEN}

workflows:
  version: 2
  format_and_lint:
    jobs:
      - test_files
      # - setup
      # - format_and_lint:
      #     requires:
      #       - setup
      # - build:
      #     requires:
      #       - setup
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - main
      # - deploy:
      #     name: deploy_dev
      #     env: dev
      #     context: FIREBASE
      #     requires:
      #       - format_and_lint
      #       - build
      #     filters:
      #       branches:
      #         only: develop
      # - deploy:
      #     name: deploy_prod
      #     env: prod
      #     context: FIREBASE
      #     requires:
      #       - format_and_lint
      #       - build
      #     filters:
      #       branches:
      #         only: main