name: Check before release

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@47f7cf65b5ced0830a325f705cad64f2f58dddf7
        with:
         script: |
           github.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: 'mainブランチへのPRは自動的に本番環境へデプロイされます。以下の内容を確認してください。\n- [skip ci]というメッセを含んだコミットによりバージョン番号がインクリメントされていること'
           })
